sudo: required
services:
    - docker
language: java
install: true
script: mvn clean package -DskipTests=true
deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "backend"
    env: "Backend-env"
    bucket_name: "elasticbeanstalk-ap-south-1-509006680370"
    bucket_path: "backend"
    edge: true
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY